// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApvkusb7wbfJtUT92KWXFPmp6dejPrFCA',
    appId: '1:809284548887:web:e61c44f60f4c0398555f52',
    messagingSenderId: '809284548887',
    projectId: 'chatapp-ca6b8',
    authDomain: 'chatapp-ca6b8.firebaseapp.com',
    storageBucket: 'chatapp-ca6b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusMuLS8BmhWEQTp4Ej_HvzWAe1KgOt3o',
    appId: '1:809284548887:android:387e6f5e2dcafdfd555f52',
    messagingSenderId: '809284548887',
    projectId: 'chatapp-ca6b8',
    storageBucket: 'chatapp-ca6b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsO5xB9AX4FXVMgzAS2IZbNY-RJy3Hs6s',
    appId: '1:809284548887:ios:d11879b6c0bc7b53555f52',
    messagingSenderId: '809284548887',
    projectId: 'chatapp-ca6b8',
    storageBucket: 'chatapp-ca6b8.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsO5xB9AX4FXVMgzAS2IZbNY-RJy3Hs6s',
    appId: '1:809284548887:ios:f4791137c33e12b2555f52',
    messagingSenderId: '809284548887',
    projectId: 'chatapp-ca6b8',
    storageBucket: 'chatapp-ca6b8.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
